// ******************************************************************
// ----------------- TECHNICAL UNIVERSITY OF KOSICE -----------------
// ---Department of Electronics and Multimedia Telecommunications ---
// -------- FACULTY OF ELECTRICAL ENGINEERING AND INFORMATICS -------
// ------------ THIS CODE IS A PART OF A MASTER'S THESIS ------------
// ------------------------- Master thesis --------------------------
// -----------------Patrik Zelenak & Milos Drutarovsky --------------
// ---------------------------version 1.0.0 -------------------------
// --------------------------- 07-03-2024 ---------------------------
// ******************************************************************

#include "importer.h"

// SERVER side

// Variables that the server already has:
//  - RegistrationRequest request;
//  - uint8_t *server_public_key;
//  - uint8_t *credential_identifier;
//  - uint8_t *oprf_seed;

// Variables that the server generates in this phase:
//  - RegistrationResponse response;


int main()
{
	/** 
    * This file describes second step of OPAQUE offline registration
	  * phase, which is registration response (see offline_reg_step_1.c).
    * Creation of registration response is made on server-side and it
    * uses RegistrationRequest structure created and sent by Clinet in
    * previous step. RegistrationResponse can be created with function
    * called ServerRegistrationResponse()
    *  
    * Input:
    *   - request, a RegistrationRequest structure.
    *   - server_public_key, the server's public key.
    *   - credential_identifier, an identifier that uniquely represents the credential.
    *   - oprf_seed, the seed of Nh bytes used by the server to generate an oprf_key.
    * Output:
    *   - response, a RegistrationResponse structure.
	**/

  // 1.2) Server create resp.
  ServerRegistrationResponse(
    &response,
    &request,
    server_public_key,
    credential_identifier, credential_identifier_len,
    oprf_seed
  );

/**
  * Registration part of OPAQUE protocol detailed:
  * --------------------------------------------------------
  *  def CreateRegistrationResponse(request, server_public_key,
  *                               credential_identifier, oprf_seed):
  *   seed = Expand(oprf_seed, concat(credential_identifier, "OprfKey"), Nok)
  *  (oprf_key, _) = DeriveKeyPair(seed, "OPAQUE-DeriveKeyPair")
  *
  *   blinded_element = DeserializeElement(request.blinded_message)
  *   evaluated_element = BlindEvaluate(oprf_key, blinded_element)
  *   evaluated_message = SerializeElement(evaluated_element)
  *
  *   Create RegistrationResponse response with 
  *   (evaluated_message, server_public_key)
  *   return response

  *  Note that all this function does is just a simple multiplication of blinded_element
  *  depicted as M (from "OPRF Signing phase" step 3, see file offline_reg_step_1.c)
  *  by secret key x, which is really what's written in step 4 in "OPRF Signing 
  *  phase" => Z = xM.

  *  An 'x' is secret key (oprf_key) which is generated in really specific way.
  *  First we 'expand' [credential_identifier+"OprfKey"] using hkdfExpand function 
  *  [https://datatracker.ietf.org/doc/html/rfc5869]
  *  based on sha512. Result of such expansion (seed) is uniformly distributed 
  *  (random-looking) byte array of length Nok=32. 
  *  Then we derivate 'x' (oprf_key) from seed computed from previous step using DeriveKeyPair
  *  function [https://www.ietf.org/archive/id/draft-irtf-cfrg-voprf-21.html#section-3.2.1].
  *  * A unique identifier is identifier for the client's credential, generated by the server
  *  (could be uuid or smth).

  *  Lastly we need to multipy M (computed in step 3 of "OPRF Signing phase") 
  *  by secret key 'x' (oprf_key). This is done by BlindEvaluate() which is
  *  really just multiplication of ristretto255_point by scalar 'x'. 
  *  Note that to get ristretto255_point from ristretto255 byte-array element
  *  we need to first DeserializeElement and then multiply using BlindEvaluate. After 
  *  multiplication we deserialize ristretto255_point back to byte-array element.
**/ 

	return 0;
}